version: "3.9"

services:

    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    #     ports:
    #         - "9200:9200"
    #     volumes:
    #         - elasticsearch

    postgres:
        image: postgres:13.3
        container_name: postgres
        ports:
            - "5432:5432"
        env_file:
            - ./backend/.env
        volumes:
            - postgres-db:/var/lib/postgresql/data
        networks:
            - teamatch-network

    backend:
        container_name: "fastapi"
        image: teamatch_backend:latest
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend
        restart: always
        environment:
            - WATCHFILES_FORCE_POLLING=true
            - GUNICORN_WORKERS=1
            - JSON_LOGS=0
            - LOG_LEVEL=DEBUG
            - PRE_COMMIT_HOME=/backend/.pre-commit
            - ENV=dev
        tty: true
        depends_on:
            - postgres
        networks:
            - teamatch-network


    matching:
        container_name: matching
        build:
            context: ./backend/microservices/matching
        ports:
            - "8001:8001"
        volumes:
            - ./backend:/backend
        restart: always
        tty: true
        depends_on:
            - postgres
        networks:
            - teamatch-network


volumes:
    postgres-db:
networks:
    teamatch-network:
        driver: bridge

