name: precomit

on:
  push:
    branches:
      - '!master'
      - '!develop'
      - '*'


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
