apiVersion: v1
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: "120"
  ADMIN_EMAIL: admin@sdm-teamatch.com
  ADMIN_NAME: admin
  ADMIN_PASSWORD: "1234"
  CLIENT_ORIGIN: http://0.0.0.0:8000/
  DATABASE_PORT: "5432"
  ENV: prod
  GOOGLE_CLIENT_ID: 768305533256-eg3ift96spolgtm69bo6r3423df13c73.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  GOOGLE_SECRET_KEY: T8B5KM9ae3UrV3-CWbmXaDlyVTTFYuimJx5J39NY
  GUNICORN_WORKERS: "1"
  JSON_LOGS: "0"
  JWT_ALGORITHM: RS256
  JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT0FJQkFBSkFSSXIyUmRuSnVuRHNBR1FMdkV2eUJIUkpBWUsxd05mS25DNUNLSE9Hd1g4dzlLSGlWTG5tCm82TjQ2OEljYWJBS0RxSGErRWtNOFh6Undya2pmSzRmVVFJREFRQUJBa0FUV1BKSkp6K1UrL2p4NTB1VXZBODEKaUtsdTNybDFGTFJoUDRGM0w1enpFeXd4dTBVZWlqQ0t4TTBhRitMazd1NlRyamQ3c2xBckx6ZFpnM3dpWGwzQgpBaUVBaGhiYm5nL05KTDFnM053bjBTclJxOHI0NGE0cTI4S1lBa1JGQnFNMUdKa0NJUUNDM0R0aWUwUENiUWVJCjA2ZDBZRmk0ME1aa2NXRjl0Q1BrcTdWQmUzWFhlUUlnVXZZcGd5MzdtdE9nN29VNERXNFVzOW10Q3RTYnA4UksKRUh6MHlCcUthMkVDSUZHWVFPOEhMUmp1SXVTT0ZMdmIxM1psdDA2cDQ4QWRzc1BDelNJbmVUTUJBaUJwRnE5KwpIbTVTU0dtWklxUEVDV1l4UVdlNnY5MVVRdzRwNUdRMlRVRTUwZz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZzd0RRWUpLb1pJaHZjTkFRRUJCUUFEU2dBd1J3SkFSSXIyUmRuSnVuRHNBR1FMdkV2eUJIUkpBWUsxd05mSwpuQzVDS0hPR3dYOHc5S0hpVkxubW82TjQ2OEljYWJBS0RxSGErRWtNOFh6Undya2pmSzRmVVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
  LOG_LEVEL: DEBUG
  POOL_SIZE: "1"
  POSTGRES_DB: fastapi
  POSTGRES_HOST: postgres
  POSTGRES_HOSTNAME: 0.0.0.0
  POSTGRES_PASSWORD: password123
  POSTGRES_USER: postgres
  PRE_COMMIT_HOME: /backend/.pre-commit
  RABBITMQ_HOST: rabbitmq-container
  REFRESH_TOKEN_EXPIRE_MINUTES: "60"
  SECRET_KEY: a39545e93ee50f5360c4467d0f902a1cb27df372f8335291ea878fd4abd7f018
  SESSION_DURATION: "60"
  WATCHFILES_FORCE_POLLING: "true"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-backend--env
  name: backend--env
