apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/bobo/Code/sdm-project/backend/"
